### ISSUE TITLE
Make Demos CI Code More DRY and Manageable

### ISSUE THREAD

**Issue by jasonkuhrt** [the-guild-org/polen#96]
# Make Demos CI Code More DRY and Manageable

## Overview

The current demos CI implementation has grown organically and contains significant duplication across workflows. This issue proposes several approaches to consolidate and simplify the codebase.

## Current Pain Points

1. **Duplicated Logic**: Path updates, deployment logic, and index updates are repeated across workflows
2. **Scattered Scripts**: Scripts in `.github/scripts/` have unclear organization
3. **Repeated Build Steps**: Similar build sequences appear in multiple workflows
4. **Complex Path Management**: Base path updates using perl are duplicated
5. **Index Update Logic**: Similar index update code in multiple places

### 1. Centralize Common Build Logic into a Composite Action

Create `.github/actions/build-demos/action.yml`:

```yaml
name: 'Build Polen Demos'
description: 'Build demos with configurable base paths'
inputs:
  examples:
    description: 'Space-separated list of examples to build'
    required: true
  base-path-prefix:
    description: 'Base path prefix (e.g., /polen/1.2.0)'
    required: true
  output-dir:
    description: 'Output directory for built demos'
    default: 'demos-build'
runs:
  using: 'composite'
  steps:
    - name: Build demos
      shell: bash
      run: |
        for example in ${{ inputs.examples }}; do
          echo "Building $example..."
          pnpm --dir examples/$example build --base "${{ inputs.base-path-prefix }}/$example/"
          mkdir -p ${{ inputs.output-dir }}/$example
          cp -r examples/$example/build/* ${{ inputs.output-dir }}/$example/
        done
```

### 2. Consolidate Path Updates into a Dedicated Script

Create `.github/scripts/lib/update-paths.js`:

```javascript
import { promises as fs } from 'node:fs'
import { join } from 'node:path'
import { glob } from 'tiny-globby'

export async function updatePaths(directory, fromPath, toPath) {
  const files = await glob(['**/*.{html,js,css,json}'], {
    cwd: directory,
    absolute: true
  })
  
  for (const file of files) {
    const content = await fs.readFile(file, 'utf8')
    const updated = content.replace(
      new RegExp(escapeRegex(fromPath), 'g'),
      toPath
    )
    if (content !== updated) {
      await fs.writeFile(file, updated)
    }
  }
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
```

### 3. Create a Unified Demos Manager Script

Create `.github/scripts/tools/demos-manager.js`:

```javascript
import { Command } from 'commander'
import { updatePaths } from '../lib/update-paths.js'
import { buildDemosIndex } from '../lib/build-index.js'
import { getDemoExamples } from '../lib/get-examples.js'

const program = new Command()

program
  .command('copy-deployment')
  .description('Copy deployment and update paths')
  .option('--from <path>', 'Source path')
  .option('--to <path>', 'Destination path')
  .option('--from-base <base>', 'From base path in content')
  .option('--to-base <base>', 'To base path in content')
  .action(async (options) => {
    await fs.cp(options.from, options.to, { recursive: true })
    await updatePaths(options.to, options.fromBase, options.toBase)
  })

program
  .command('update-dist-tag')
  .description('Update dist-tag content')
  .option('--tag <tag>', 'Dist tag name')
  .option('--version <version>', 'Semver version')
  .option('--gh-pages <path>', 'Path to gh-pages')
  .action(async (options) => {
    const { tag, version, ghPages } = options
    const tagPath = join(ghPages, tag)
    const versionPath = join(ghPages, version)
    
    if (await fs.exists(tagPath)) {
      await fs.rm(tagPath, { recursive: true })
    }
    
    await fs.cp(versionPath, tagPath, { recursive: true })
    await updatePaths(tagPath, `/polen/${version}/`, `/polen/${tag}/`)
  })

// ... more commands

program.parse()
```

### 4. Simplify Workflows with Matrix Strategy

Update workflows to use matrix builds:

```yaml
jobs:
  build-demos:
    strategy:
      matrix:
        example: ${{ fromJson(needs.get-examples.outputs.examples) }}
    steps:
      - uses: ./.github/actions/build-demos
        with:
          examples: ${{ matrix.example }}
          base-path-prefix: /polen/${{ steps.version.outputs.tag }}
```

### 5. Configuration-Driven Approach

Extend `.github/demo-config.json`:

```json
{
  "excludeDemos": ["github"],
  "minimumVersion": "0.9.0",
  "examples": {
    "pokemon": {
      "title": "Pokemon API",
      "description": "Explore a fun GraphQL API...",
      "enabled": true
    },
    "github": {
      "title": "GitHub API",
      "description": "Browse GitHub's extensive...",
      "enabled": false,
      "disabledReason": "Build performance"
    }
  },
  "deployment": {
    "distTags": ["latest", "next"],
    "keepPreviousCount": 10
  }
}
```

### 6. Abstract GitHub Pages Operations

Create `.github/scripts/lib/gh-pages.js`:

```javascript
export class GitHubPagesManager {
  constructor(repoPath) {
    this.repoPath = repoPath
  }
  
  async listDeployments(pattern) {
    // List deployments matching pattern
  }
  
  async deploymentExists(path) {
    // Check if deployment exists
  }
  
  async copyDeployment(from, to, pathUpdates) {
    // Copy and update paths atomically
  }
  
  async removeDeployment(path) {
    // Remove deployment
  }
  
  async getDistTagTarget(tag) {
    // Detect what version a dist-tag points to
  }
}
```

### 7. Standardize Script Structure

Reorganize scripts following consistent patterns:

```
.github/
  scripts/
    lib/              # Shared libraries
      gh-pages.js
      update-paths.js
      build-index.js
    steps/            # Workflow steps (simple scripts)
      update-demos-index.js
      get-previous-deployments.js
    tools/            # CLI tools
      demos-manager.js
      validate-config.js
```

## Benefits

1. **Reduced Duplication**: Common logic in one place
2. **Easier Testing**: Isolated functions can be unit tested
3. **Better Maintainability**: Clear separation of concerns
4. **Improved Reliability**: Centralized error handling
5. **Faster Development**: Reusable components

## Implementation Priority

1. Start with path update consolidation (highest impact)
2. Create demos manager script
3. Refactor workflows to use new tools
4. Add configuration validation
5. Implement comprehensive error handling

## Next Steps

- Review and prioritize proposals
- Create implementation plan
- Start with smallest, highest-impact changes
- Gradually refactor existing workflows
